# Generated by Django 5.2.4 on 2025-11-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_group_post_is_chat_message_post_is_pinned_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
