# Generated by Django 5.2.4 on 2025-12-26 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_delete_repost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chat_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_value',
            field=models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')]),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post'], name='posts_like_post_id_db9889_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='posts_post_created_dadbfe_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='posts_post_author__19d68b_idx'),
        ),
        migrations.AddConstraint(
            model_name='postmedia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image__isnull', False), ('media_type', 'image')), models.Q(('file__isnull', False), ('media_type', 'video')), models.Q(('file__isnull', False), ('media_type', 'file')), models.Q(('media_type', 'link'), ('url__isnull', False)), _connector='OR'), name='postmedia_valid_content'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
