# Generated by Django 5.2.7 on 2025-10-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_post_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
