# Generated by Django 5.2.4 on 2025-10-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='image',
        ),
        migrations.AddField(
            model_name='grouppost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='group_files/'),
        ),
    ]
